---
##
# nginx installation.
#
- name: General | Install required packages.
  action: apt pkg=nginx state=installed

- name: nginx | Create nginx group
  action: group name=nginx system=yes

- name: nginx | Create a user for nginx otherwise www-data is shared with Apache
  action: user name=nginx group=nginx createhome=no system=yes

- name: Add mime types for nginx including our font type WOFF
  action: copy src=nginx/files/etc-nginx-mime-types dest=/etc/nginx/mime.types

- name: Configure nginx
  action: template src=nginx/templates/etc-nginx-nginx-conf.j2 dest=/etc/nginx/nginx.conf

- name: Update default site
  action: template src=nginx/templates/etc-nginx-sites-available-default.j2 dest=/etc/nginx/sites-available/default

- name: Enable default site
  action: file path=/etc/nginx/sites-enabled/default src=/etc/nginx/sites-available/default state=link

- name: Restart nginx
  action: service name=nginx state=restarted
