---
# The main playbook to deploy the site

- hosts: development
  sudo: yes
  roles:
    - bender

- hosts: all
  sudo: yes
  roles:
   - common
   - cache
   - db
   - search
   - { role: ANXS.nodejs, nodejs_version: "0.12.4", nodejs_install_method: "binary" }
   - { role: zzet.rbenv, tags: ["ruby"]}
   - { role: geerlingguy.redis }
   - web
   - training
