##
# Ansible playbook for setting up dev2.
#

---
- hosts: all
  user: root

  vars_files:
    - settings.yml

  tasks:
    ##
    # Apt package installation of required software.
    #
    - name: General | Install required packages.
      action: apt pkg=$item state=installed
      tags: common
      with_items:
        - php5
        - apache2
        - mysql-server
        - mysql-client
        - php5-mysql
        - php-apc
        - php5-xmlrpc
        - php-soap
        - php5-gd
        - sendmail
        - unzip
        - python-mysqldb
        - etckeeper

    ##
    # Message of the day configuration.
    #
    - name: General | Message of the day explaining server is under Ansible control.
      action: copy src=files/etc-update-motd-d-95-ansible dest=/etc/update-motd.d/95-ansible mode=755
      tags: common

    - name: General | Message of the day logo script.
      action: copy src=files/etc-update-motd-d-05-splash dest=/etc/update-motd.d/05-splash mode=755
      tags: common

    - name: General | Message of the day logo file.
      action: copy src=files/dev2-terminal-logo dest=/etc/update-motd.d/dev2-terminal-logo mode=644
      tags: common

    - name: General | Disable default motd scripts.
      action: file path=/etc/update-motd.d/00-header mode=444
      tags: common

    - name: General | Disable default motd scripts.
      action: file path=/etc/update-motd.d/10-help-text mode=444
      tags: common

    - name: General | Disable default motd scripts.
      action: file path=/etc/update-motd.d/50-landscape-sysinfo state=absent
      tags: common

    ##
    # Etckeeper
    #
    - name: etckeeper | Configuration file
      action: copy src=files/etc-etckeeper-etckeeper-conf.j2 dest=/etc/etckeeper/etckeeper.conf
      tags: common

    - name: etckeeper | Initialize.
      action: command etckeeper init creates=/etc/.git
      tags: common

    ##
    # PHP Setup.
    #
    - name: PHP | Configuration file - php.ini
      action: template src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
      tags: common

    - name: APC | Cache configuration file - apc.ini
      action: template src=templates/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
      tags: common

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file - my.cnf
      action: template src=templates/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
      tags: common

    - include: lib/mysql-secure.yml tags=common

    ##
    # Apache2 setup.
    #
    - name: Apache | Enable some required modules
      action: command a2enmod rewrite vhost_alias
      tags: common

    - name: Apache | Configuration file for our site
      action: template src=templates/etc-apache2-sites-available-devserver.j2 dest=/etc/apache2/sites-available/devserver
      tags: common

    - name: Apache | Disable the default site
      action: command a2dissite default
      tags: common

    - name: Apache | Enable our new site
      action: command a2ensite devserver
      tags: common

    - name: Apache | Robots.txt file that prevents search engines from spidering dev site.
      action: copy src=files/var-www-robots-txt dest=/var/www/robots.txt
      tags: common

    - name: Apache | htaccess file for user access control.
      action: copy src=files/etc-apache2-htpasswd dest=/etc/apache2/htpasswd
      tags: common

    ##
    # Drush install, a Drupal shell tool.
    #
    - include: lib/drush.yml tags=drush

    ##
    # node.js installation (latest stable instead of Ubuntu's out-of-date one)
    #
    - name: Node.js | Package prerequisites for node.js
      action: apt pkg=python-software-properties state=installed
      tags: nodejs

    - name: Node.js | Add the node.js PPA
      action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list
      tags: nodejs

    - name: Node.js | Update the apt cache for the new repository
      action: apt update-cache=yes
      tags: nodejs

    - name: Node.js | Install nodejs and npm
      action: apt pkg=$item state=installed
      tags: nodejs
      with_items:
        - nodejs
        - npm

    ##
    # Redis server.
    #
    - name: Redis | Install redis
      action: apt pkg=redis-server state=installed
      tags: redis

    ##
    # CSS compiling tools.
    #
    - name: CSS | Install rubygems package
      action: apt pkg=rubygems state=installed
      tags: css

    - name: CSS | Install SASS
      action: command gem install sass creates=/usr/local/bin/sass
      tags: css

    - name: CSS | Install Susy (no more --pre required as it's 1.0 now)
      action: command gem install susy
      tags: css

    - name: CSS | Install Compass
      action: command gem install compass creates=/usr/local/bin/compass
      tags: css

    - name: CSS | Install Respond-to
      action: command gem install respond-to
      tags: css

    ##
    # Dotcloud support
    #
    - name: Dotcloud | Python pip for dotcloud
      action: apt pkg=python-pip state=installed
      tags: dotcloud

    - name: Dotcloud | Install dotcloud cli
      action: command pip install dotcloud creates=/usr/local/bin/dotcloud
      tags: dotcloud

    ##
    # Remove extra tty terminals
    #
    - include: lib/tty.yml tags=common

    ##
    # Memcache
    #
    - include: lib/memcache.yml tags=memcache

    ##
    # Restart services
    #
    - name: Restart Apache
      action: service name=apache2 state=restarted
      tags: common

    - name: Restart MySQL
      action: service name=mysql state=restarted
      tags: common

    - name: Restart Memcache
      action: service name=memcached state=restarted
      tags: memcache
















