##
# Ansible playbook for setting up dev2.
#

---
- hosts: all
  user: root

  vars_files:
    - settings.yml

  tasks:
    ##
    # Apt package installation of required software.
    #
    - name: General | Install required packages.
      action: apt pkg=$item state=installed
      tags: common
      with_items:
        - php5
        - apache2
        - mysql-server
        - mysql-client
        - php5-mysql
        - php-apc
        - php5-xmlrpc
        - php-soap
        - php5-gd
        - sendmail
        - unzip
        - python-mysqldb
        - etckeeper

    ##
    # Message of the day configuration.
    #
    - name: General | Message of the day explaining server is under Ansible control.
      action: copy src=files/etc-update-motd-d-95-ansible dest=/etc/update-motd.d/95-ansible mode=755
      tags: common

    - name: General | Message of the day logo script.
      action: copy src=files/etc-update-motd-d-05-splash dest=/etc/update-motd.d/05-splash mode=755
      tags: common

    - name: General | Message of the day logo file.
      action: copy src=files/dev2-terminal-logo dest=/etc/update-motd.d/dev2-terminal-logo mode=644
      tags: common

    - name: General | Disable default motd scripts.
      action: file path=/etc/update-motd.d/00-header mode=444
      tags: common

    - name: General | Disable default motd scripts.
      action: file path=/etc/update-motd.d/10-help-text mode=444
      tags: common

    - name: General | Disable default motd scripts.
      action: file path=/etc/update-motd.d/50-landscape-sysinfo state=absent
      tags: common

    ##
    # Etckeeper
    #
    - name: etckeeper | Configuration file
      action: copy src=files/etc-etckeeper-etckeeper-conf.j2 dest=/etc/etckeeper/etckeeper.conf
      tags: common

    - name: etckeeper | Initialize.
      action: command etckeeper init creates=/etc/.git
      tags: common

    ##
    # PHP Setup.
    #
    - name: PHP | Configuration file - php.ini
      action: template src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
      tags: common

    - name: APC | Cache configuration file - apc.ini
      action: template src=templates/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
      tags: common

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file - my.cnf
      action: template src=templates/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
      tags: common

    - include: ../common-tasks/mysql-secure.yml
















