---
##
# Memcached daemon and PECL extension. We don't make any changes to the
# default config files, so those aren't here yet.
#
- name: Memcached | Install packages
  action: apt pkg=$item state=installed
  with_items:
    - php5-memcache
    - memcached

- name: Restart Memcache
  action: service name=memcached state=restarted
