---
##
# Add a new user.
#
# user_name: The name of the new user, will also be used for group name.
# fetch_key: Boolean that is used to fetch the users key.
# user_mail: The user's email address as set on fourkitchens.com. Used for authorized_keys.
#
# This playbook is meant to work as a parametized build in Jenkins.
# The job should have parameters for the above variables, using text for
# user_name, user_mail and key, and a boolean for fetch_key.
# Below is the bash script that would be used in the script box.
#
#!/bin/bash
#
#cd /home/bender/dev2-playbooks
#
#if [ $fetch_key == true ]; then
#  ansible-playbook -s -i hosts --connection=local --extra-vars="user_name=$user_name fetch_key=true user_mail='$user_mail'" deploy/users/user-add-tower.yml
#else
#  ansible-playbook -s -i hosts --connection=local --extra-vars="user_name=$user_name key='$key'" deploy/users/user-add-tower.yml
#fi
#


- hosts: all
  user: root
  vars:
    fetch_key: 'false'

  tasks:

    - name: Create user group.
      action: group name={{user_name}}

    - name: Create the user account.
      action: user name={{user_name}} groups={{user_name}},rvm shell=/bin/bash state=present

    - name: SSH Folder.
      action: file path=/home/{{user_name}}/.ssh state=directory owner={{user_name}} group={{user_name}} mode=755

    - name: WWW Folder.
      action: file path=/home/{{user_name}}/www state=directory owner={{user_name}} group={{user_name}} mode=755

    - name: Authorized keys from 4K.com
      action: get_url thirsty=yes url=http://fourkitchens.com/authorized_keys?mail={{user_mail}} dest=/home/{{user_name}}/.ssh/authorized_keys owner={{user_name}} group={{user_name}} mode=644
      when: fetch_key == 'true'

    - name: Authorized keys from string
      action: authorized_key user={{ user_name }}
                             key="{{ key }}"
      when: fetch_key == 'false'
