---
##
# Add a new user.
#
# user_name: The name of the new user, will also be used for group name.
# github: The GitHub username.
#
- hosts: all
  sudo: yes

  vars_prompt:
    user_name: "What should the username be?"
    github: "What is their GitHub user? (for authorized_keys)"

  tasks:
    - name: Create user group.
      action: group name={{ user_name }}

    - name: Create the user account.
      action: user name={{ user_name }} groups={{ user_name }} shell=/bin/bash state=present

    - name: SSH Folder.
      action: file path=/home/{{ user_name }}/.ssh state=directory owner={{ user_name }} group={{ user_name }} mode=755

    - name: WWW Folder.
      action: file path=/home/{{ user_name }}/www state=directory owner={{ user_name }} group={{ user_name }} mode=755

    - name: Authorized keys from GitHub
      action: get_url thirsty=yes url=https://github.com/{{ github }}.keys dest=/home/{{ user_name }}/.ssh/authorized_keys owner={{ user_name }} group={{ user_name }} mode=644
