---
##
# Apt package installation of required software.
#
- name: General | Install required packages.
  action: apt pkg=$item state=installed
  with_items:
    - php5
    - apache2
    - mysql-server
    - mysql-client
    - php5-mysql
    - php-apc
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - python-mysqldb

##
# PHP Setup.
#
- name: PHP | Configuration file - php.ini
  action: template src=lamp/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini

- name: APC | Cache configuration file - apc.ini
  action: template src=lamp/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini

##
# MySQL database setup.
#
- name: MySQL | Configuration file - my.cnf
  action: template src=lamp/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf

##
# This does the equivalent of mysql_secure_installation.
#
- name: MySQL | Set the root password.
  action: mysql_user user=root password=$mysql_root_password host=localhost

- name: MySQL | Config for easy access as root user
  action: template src=lamp/root-my-cnf.j2 dest=/root/.my.cnf

- name: MySQL | Delete anonymous MySQL server user for $server_hostname
  action: mysql_user user="" host="$server_hostname" state="absent"

- name: MySQL | Delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: MySQL | Secure the MySQL root user for IPV6 localhost (::1)
  action: mysql_user user="root" password="$mysql_root_password" host="::1"

- name: MySQL | Secure the MySQL root user for IPV4 localhost (127.0.0.1)
  action: mysql_user user="root" password="$mysql_root_password" host="127.0.0.1"

- name: MySQL | Secure the MySQL root user for localhost domain (localhost)
  action: mysql_user user="root" password="$mysql_root_password" host="localhost"

- name: MySQL | Secure the MySQL root user for $server_hostname domain
  action: mysql_user user="root" password="$mysql_root_password" host="$server_hostname"

- name: MySQL | Remove the MySQL test database
  action: mysql_db db=test state=absent

##
# Apache2 setup.
#
- name: Apache | Enable Apache rewrite module
  action: command a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load

- name: Apache | Enable Apache vhost_alias module
  action: command a2enmod vhost_alias creates=/etc/apache2/mods-enabled/vhost_alias.load

- name: Apache | Main configuration file
  action: template src=lamp/etc-apache2-apache2-conf.j2 dest=/etc/apache2/apache2.conf

- name: Apache | Main configuration file for ports
  action: template src=lamp/etc-apache2-ports-conf.j2 dest=/etc/apache2/ports.conf

- name: Apache | Configuration file for our devserver site
  action: template src=lamp/etc-apache2-sites-available-devserver.j2 dest=/etc/apache2/sites-available/devserver

- name: Apache | Disable the default site
  action: command a2dissite default removes=/etc/apache2/sites-enabled/default

- name: Apache | Enable our new devserver site
  action: command a2ensite devserver creates=/etc/apache2/sites-enabled/devserver

- name: Apache | Robots.txt file that prevents search engines from spidering dev site.
  action: copy src=lamp/var-www-robots-txt dest=/var/www/robots.txt

- name: Apache | htaccess file for user access control.
  action: copy src=lamp/etc-apache2-htpasswd dest=/etc/apache2/htpasswd

- name: Apache | Directory for virtual hosts.
  action: file path=/var/www/vhosts state=directory mode=755 owner=bender group=bender

##
# The home page of the server, mostly for people who are lost.
#
- name: Apache | Clone the repo for the home site.
  action: git repo=git@github.com:fourkitchens/dev-server-landing.git dest=/var/www/home version=master

- name: Apache | Make Bender the owner of the home site.
  action: "command chown -R bender: /var/www/home"

- name: Apache | Configuration file for the home site.
  action: template src=lamp/etc-apache2-sites-available-home.j2 dest=/etc/apache2/sites-available/home

- name: Apache | Enable our new home site
  action: command a2ensite home creates=/etc/apache2/sites-enabled/home

##
# Restart services
#
- name: Restart Apache
  action: service name=apache2 state=restarted

- name: Restart MySQL
  action: service name=mysql state=restarted
