# Settings that are applied to the templates. This file should be copied to
# the base folder of the play and renamed settings.yml, then modified to suit
# your needs.

---
# Hostname is important as we need to delete an anonymous MySQL
# user that is created with this name, make sure you match this
# up with the output of the command 'hostname' on the server.
server_hostname: 'local.dev'

# php.ini
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'US/Central'
php_memory_limit: '256M'
# apc.ini
apc_rfc1867: '1'
apc_shm_size: '90M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# my.cnf
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# mysql
mysql_root_password: 'password'

# apache
apache_port: 8080
apache_server_admin: 'you@fourkitchens.com'
apache_server_alias: '*.*.local.dev'
apache_server_virtual_docroot: '/home/%-4/www/%-3'
apache_server_directory: '/home/*/www/*'
apache_server_name: 'local'
apache_server_home_alias: 'local.dev'
apache_server_home_docroot: '/var/www/home'

# varnish
varnish_port: 80
varnish_size: '1G'
varnish_auth: 'Basic Zms6ZmtidWlsZA=='

# ssh
ssh_password_auth: 'no'
