---
###
# Boris
#

- name: Boris | Clone repository 
  action: git repo=https://github.com/d11wtq/boris.git dest=/usr/local/share/boris version=v1.0.8

- name: Boris | Create symlink in /usr/local/bin
  action: shell creates=/usr/local/bin/boris ln -s /usr/local/share/boris/bin/boris /usr/local/bin/boris

- name: boris-loader | Clone repository
  action: git repo=https://github.com/tobiassjosten/boris-loader.git dest=/home/vagrant/boris-loader

- name: boris-loader | Create .borisrc
  action: template src=boris/borisrc.j2 dest=/home/vagrant/.borisrc

