---
##
# CSS compiling tools.
#
- name: CSS | Install rubygems package
  action: apt pkg=rubygems state=installed

- name: SASS | Install Sass and all ruby gems
  action: gem name=$item state=latest
  with_items:
    - sass
    - compass
    - singularitygs
    - susy
    - toolkit
    - respond-to
    - breakpoint
    - compass-aurora
    - color-schemer

- name: SASS | Install Animation (pre-release)
  action: command gem install animation --pre

- name: Roole | Install Roole
  action: command npm install roole -g

