---
##
# Etckeeper
#
- name: etckeeper | Install required packages.
  action: apt pkg=etckeeper state=installed

- name: etckeeper | Configuration file
  action: copy src=etckeeper/etc-etckeeper-etckeeper-conf.j2 dest=/etc/etckeeper/etckeeper.conf

- name: etckeeper | Initialize.
  action: command etckeeper init creates=/etc/.git
