---
- name: restart apache
  service: name=apache2 state=restarted

- name: restart nginx
  service: name=nginx state=restarted

- name: restart php-fpm
  service: name=php5-fpm state=restarted

- name: restart varnish
  service: name=varnish state=restarted
