---
##
# Ansible playbook for setting up dev2.
#
- hosts: localhost
  connection: local
  user: root

  vars_files:
    - settings.yml

  tasks:
    - include: sendmail/sendmail.yml tags=sendmail
    - include: motd/motd.yml tags=motd
    - include: etckeeper/etckeeper.yml tags=etckeeper
    - include: users/bender.yml tags=users
    - include: lamp/lamp.yml tags=lamp
    - include: drush/drush.yml tags=drush
    - include: nodejs/nodejs.yml tags=nodejs
    - include: redis/redis.yml tags=redis
    - include: css-tools/css.yml tags=css
    - include: dotcloud/dotcloud.yml tags=dotcloud
    - include: linux/tty.yml tags=tty
    - include: linux/ntp.yml tags=ntp
    - include: memcache/memcache.yml tags=memcache
    - include: ssh/ssh.yml tags=ssh
