---
##
# Ansible playbook for setting up dev2.
#
- hosts: localhost
  connection: local
  user: root

  vars_files:
    - settings.yml

  tasks:
    - include: sendmail/sendmail.yml tags=sendmail
    - include: motd/motd.yml tags=motd
    - include: etckeeper/etckeeper.yml tags=etckeeper
    - include: users/bender.yml tags=users
    - include: lamp/lamp.yml tags=lamp
    - include: nginx/nginx.yml tags=nginx
    - include: drush/drush.yml tags=drush
    - include: nodejs/nodejs.yml tags=nodejs
    - include: redis/redis.yml tags=redis
    - include: ruby/ruby.yml tags=ruby
    - include: dotcloud/dotcloud.yml tags=dotcloud
    - include: linux/tty.yml tags=tty
    - include: linux/ntp.yml tags=ntp
    - include: memcache/memcache.yml tags=memcache
    - include: ssh/ssh.yml tags=ssh
    - include: varnish/varnish.yml tags=varnish
    - include: mongo/mongo.yml tags=mongodb
    - include: solr/solr.yml tags=solr
    - include: editors/editors.yml tags=vim,emacs,editors
    - include: mc/mc.yml tags=mc

  handlers:
    - name: restart tomcat
      service: name=tomcat6 state=restarted
