---
- name: checking that RVM is installed
  file:
    path: "{{rvm.init_script}}"
    state: file
  ignore_errors: True
  register: rvm_install_result
- include: ./install_rvm.yml
  when: rvm_install_result | failed

- include: ./select_ruby.yml
- include: ./install_ruby.yml
  when: rvm_select_ruby_version | failed
