---
- name: setting default Ruby version
  shell: "source {{rvm.init_script}} && rvm use {{rvm.ruby_version}} --default executable=/bin/bash"
  sudo: yes
  register: rvm_select_ruby_version
  ignore_errors: True
