---
##
# Apache2 setup.
#
- name: Apache | Install required packages
  action: apt pkg=$item state=installed
  with_items:
    - apache2
    - libapache2-mod-php5

- name: Apache | Enable Apache rewrite module
  action: command a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load

- name: Apache | Enable Apache vhost_alias module
  action: command a2enmod vhost_alias creates=/etc/apache2/mods-enabled/vhost_alias.load

- name: Apache | Enable Apache ssl module
  action: command a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load

- name: Apache | Main configuration file
  action: template src=etc/apache2/apache2.conf.j2 dest=/etc/apache2/apache2.conf

- name: Apache | Main configuration file for ports
  action: template src=etc/apache2/ports.conf.j2 dest=/etc/apache2/ports.conf

- name: Apache | Configuration file for our devserver site
  action: template src=etc/apache2/sites-available/devserver.j2 dest=/etc/apache2/sites-available/devserver

- name: Apache | Configuration file for https devserver site
  action: template src=etc/apache2/sites-available/devserver-ssl.j2 dest=/etc/apache2/sites-available/devserver-ssl

- name: Apache | Disable the default site
  action: command a2dissite default removes=/etc/apache2/sites-enabled/default

- name: Apache | Enable our new devserver site
  action: command a2ensite devserver creates=/etc/apache2/sites-enabled/devserver

- name: Apache | Enable our new https devserver site
  action: command a2ensite devserver-ssl creates=/etc/apache2/sites-enabled/devserver-ssl

- name: Apache | Robots.txt file that prevents search engines from spidering dev site.
  action: copy src=var/www/robots.txt dest=/var/www/robots.txt

- name: Apache | htaccess file for user access control.
  action: copy src=etc/apache2/htpasswd dest=/etc/apache2/htpasswd

- name: Apache | Directory for virtual hosts.
  action: file path=/var/www/vhosts state=directory mode=755 owner=bender group=bender

