---
##
# Apache2 setup.
#
- name: Apache | Add Apache 2.4 PPA
  apt_repository: repo='ppa:ondrej/apache2' update_cache=yes

- name: Apache | Install required packages
  apt: pkg=apache2 state=installed

- name: Apache | Enable Apache rewrite module
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify:
    - restart apache

- name: Apache | Enable Apache vhost_alias module
  command: a2enmod vhost_alias creates=/etc/apache2/mods-enabled/vhost_alias.load
  notify:
    - restart apache

- name: Apache | Enable Apache ssl module
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load
  notify:
    - restart apache

- name: Apache | Main configuration file
  template: src=etc/apache2/apache2.conf.j2 dest=/etc/apache2/apache2.conf
  notify:
    - restart apache

- name: Apache | Main configuration file for ports
  template: src=etc/apache2/ports.conf.j2 dest=/etc/apache2/ports.conf
  notify:
    - restart apache

- name: Apache | Configuration file for our devserver site
  template: src=etc/apache2/sites-available/devserver.conf.j2 dest=/etc/apache2/sites-available/devserver.conf
  notify:
    - restart apache

- name: Apache | Configuration file for https devserver site
  template: src=etc/apache2/sites-available/devserver-ssl.conf.j2 dest=/etc/apache2/sites-available/devserver-ssl.conf
  notify:
    - restart apache

- name: Apache | Disable the default site
  command: a2dissite default removes=/etc/apache2/sites-enabled/default
  notify:
    - restart apache

- name: Apache | Enable our new devserver site
  command: a2ensite devserver creates=/etc/apache2/sites-enabled/devserver
  notify:
    - restart apache

- name: Apache | Enable our new https devserver site
  command: a2ensite devserver-ssl creates=/etc/apache2/sites-enabled/devserver-ssl
  notify:
    - restart apache

- name: Apache | Robots.txt file that prevents search engines from spidering dev site.
  copy: src=var/www/robots.txt dest=/var/www/robots.txt
  notify:
    - restart apache

- name: Apache | htaccess file for user access control.
  copy: src=etc/apache2/htpasswd dest=/etc/apache2/htpasswd
  notify:
    - restart apache

- name: Apache | Directory for virtual hosts.
  file: path=/var/www/vhosts state=directory mode=755 owner={{ apache_vhost_user }} group={{ apache_vhost_group }}
  notify:
    - restart apache
