---
##
# Drush install, a Drupal shell tool.
# Copied 100% from https://github.com/geerlingguy/ansible-role-drush
# We cannot use the galaxy role because it depends on his php role,
# and his php role can't provide both http and fpm php installations.
#

- name: Clone Drush from GitHub.
  git: >
    repo=https://github.com/drush-ops/drush.git
    dest={{ drush_install_path }}
    version={{ drush_version }}
    update={{ drush_keep_updated }}

- name: Install Drush dependencies with Composer.
  shell: >
    {{ composer_path }} install --prefer-source --no-interaction
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php

- name: Create drush symlink.
  file: >
    src={{ drush_install_path }}/drush
    dest={{ drush_path }}
    state=link

- name: Run drush to finish setting it up.
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
