---
##
# Drush install, a Drupal shell tool.
#
- name: Drush | Install PHP PEAR
  apt: pkg=php-pear state=installed

- name: Drush | Update PEAR
  command: pear upgrade-all creates=/usr/bin/drush

- name: Drush | Setup PEAR channel
  command: pear channel-discover pear.drush.org creates=/usr/share/php/.channels/pear.drush.org.reg creates=/usr/bin/drush

- name: Drush | Install drush
  command: pear install drush/drush creates=/usr/bin/drush

- name: Drush | Run drush once so it downloads its dependencies
  command: drush creates=/usr/bin/drush

- name: Drush | Create a folder to hold site aliases
  file: path=/etc/drush state=directory
