---
##
# Drush install, a Drupal shell tool.
#

- name: Drush | Check if Drush is installed.
  shell: /usr/bin/drush
  register: drush_check
  ignore_errors: True

- name: Drush | Install PHP PEAR
  apt: pkg=php-pear state=installed
  when: drush_check|failed

- name: Drush | Update PEAR
  command: pear upgrade-all
  when: drush_check|failed

- name: Drush | Setup PEAR channel
  command: pear channel-discover pear.drush.org creates=/usr/share/php/.channels/pear.drush.org.reg
  when: drush_check|failed

- name: Drush | Install drush
  command: pear install drush/drush
  when: drush_check|failed

- name: Drush | Run drush once so it downloads its dependencies
  command: drush
  when: drush_check|failed

- name: Drush | Create a folder to hold site aliases
  file: path=/etc/drush state=directory
  when: drush_check|failed
