---
##
# nginx installation.
#
- name: General | Install required packages.
  action: apt pkg=nginx state=installed

- name: nginx | Create nginx group
  action: group name=nginx system=yes

- name: nginx | Create a user for nginx otherwise www-data is shared with Apache
  action: user name=nginx group=nginx createhome=no system=yes

- name: nginx | Add mime types for nginx including our font type WOFF
  action: copy src=etc/nginx/mime.types dest=/etc/nginx/mime.types
  notify:
    - restart nginx

- name: nginx | Configure nginx
  action: template src=etc/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
    - restart php-fpm

- name: nginx | Update default site
  action: template src=etc/nginx/sites-available/default.j2 dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: nginx | Enable default site
  action: file path=/etc/nginx/sites-enabled/99-default src=/etc/nginx/sites-available/default state=link
  notify:
    - restart nginx

- name: nginx | Update ssl site
  action: copy src=etc/nginx/sites-available/ssl dest=/etc/nginx/sites-available/ssl
  notify:
    - restart nginx

- name: nginx | Enable ssl site
  action: file path=/etc/nginx/sites-enabled/00-ssl src=/etc/nginx/sites-available/ssl state=link
  notify:
    - restart nginx

