---
##
# node.js installation (latest stable instead of Ubuntu's out-of-date one)
#
- name: Node.js | Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed

- name: Node.js | Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list

- name: Node.js | Update the apt cache for the new repository
  action: apt update-cache=yes

- name: Node.js | Install nodejs and npm
  action: apt pkg=nodejs state=installed

- name: Node.js | Install required npm packages
  action: npm name=$item global=yes
  with_items:
    - bower
    - coffee-script
    - forever
    - grunt-cli
    - jshint
    - node-inspector
    - roole
    - yo
