---
##
# node.js installation (latest stable instead of Ubuntu's out-of-date one)
#

- name: Node.js | Install required npm packages
  npm: name={{ item }} global=yes
  with_items:
    - nodemon
    - bower
    - coffee-script
    - forever
    - grunt-cli
    - jshint
    - node-inspector
    - roole
    - yo
    - drush-reloadp
