---
##
# Etckeeper
#
- name: etckeeper | Install required packages.
  apt: pkg=etckeeper state=installed

- name: etckeeper | Configuration file
  template: src=etc/etckeeper/etckeeper-conf.j2 dest=/etc/etckeeper/etckeeper.conf

- name: etckeeper | Initialize.
  command: etckeeper init creates=/etc/.git
