---
# Ensures we have a loop back to our host machine in the hosts file.


- name: Ensure we have a line to loop to our host machine in the hosts file.
  lineinfile: dest=/etc/hosts regexp='^10\.0\.1\.1' line='10.0.2.2 host_machine' owner=root group=root mode=0644
